# Generated by Django 3.2.3 on 2021-05-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='name',
            new_name='token',
        ),
    ]
