# Generated by Django 3.2.3 on 2021-05-25 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_usertoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 17, 30, 8, 818971, tzinfo=utc)),
        ),
    ]
