# Generated by Django 3.2.3 on 2021-05-25 13:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=256)),
                ('obj2', models.CharField(max_length=256)),
                ('obj1_count', models.IntegerField()),
                ('obj2_count', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 13, 16, 15, 250066, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=256)),
                ('obj2', models.CharField(max_length=256)),
                ('is_obj1', models.BooleanField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 13, 16, 15, 252701, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
